### PR TITLE
Update client_windows.go

### PR DESCRIPTION
**Pull request by christopherdiehl**
Set package name so binaries built with go mod can build the project.

### CODE REVIEW

**Comment by mperham** [comment]
Thank you!

**Comment by christopherdiehl** [comment]
@mperham is it possible to cut a new patch release to allow go mod users to build and use the client?

**Comment by mperham** [comment]
Too minor for a new version. I've force updated the v1.5.0 tag to include this fix.

**Comment by christopherdiehl** [comment]
Thank you @mperham . It looks like v1.5.0 is still including the older version of client_windows.go.

**Comment by mperham** [comment]
I can't explain what you are seeing but the v1.5.0 tag on GitHub contains the fix. https://github.com/contribsys/faktory/blob/v1.5.0/client/client_windows.go

I suspect you need to clear go mod's cache for v1.5.0.

**Comment by christopherdiehl** [comment]
Looks like the release @ https://github.com/contribsys/faktory/releases is still the old version which is why I am still experiencing failures locally.

**Comment by mperham** [comment]
Yeah, I guess me manually overriding the tag does not regenerate the
tarballs. I don’t know how to fix this. Can you pull a master or SHA
tarball? Can you shallow clone the repo at the tag?

**Comment by christopherdiehl** [comment]
Unfortunately since we’re using bazel/go mod under the hood I haven’t been
able to discover a solution that does not involve either updating the
release tarballs or cutting a release.

Please let me know if there is anything I can do on my side to help!

**Comment by christopherdiehl** [comment]
@mperham Any thoughts on how to resolve the compilation errors on the current release, and is there anything I can do to help on my side?

**Comment by mperham** [comment]
I'm working on a 1.5.1 release now.

**Comment by mperham** [comment]
Thanks for your patience, I was helping another customer with some other fixes too. 1.5.1 is now out.

https://github.com/contribsys/faktory/blob/master/Changes.md#151
